select *
from (


SELECT
RUN_DATE,
CDE_ENC_MCO,
claim_type,
cde_clm_status,
cde_clm_disposition,
ind_crossover,

SUM(PATIENTSTATUSCODE1X_NUM) AS SUM_PATIENTSTATUSCODE1X_NUM, 
SUM(PATIENTSTATUSCODE1X_DEN) AS SUM_PATIENTSTATUSCODE1X_DEN,
SUM(MEMBERID1X_NUM) AS SUM_MEMBERID1X_NUM,
SUM(MEMBERID1X_DEN) AS SUM_MEMBERID1X_DEN,
SUM(ADJUDICATIONDATEHDRX_NUM) AS SUM_ADJUDICATIONDATEHDRX_NUM,
SUM(ADJUDICATIONDATEHDRX_DEN) AS SUM_ADJUDICATIONDATEHDRX_DEN,
SUM(ADJUDICATIONDATEDTLX_NUM) AS SUM_ADJUDICATIONDATEDTLX_NUM,
SUM(ADJUDICATIONDATEDTLX_DEN) AS SUM_ADJUDICATIONDATEDTLX_DEN,
SUM(PAIDHDRSNOLINES1X_NUM) AS SUM_PAIDHDRSNOLINES1X_NUM,
SUM(PAIDHDRSNOLINES1X_DEN) AS SUM_PAIDHDRSNOLINES1X_DEN,
SUM(DENIEDHDRSNOLINES1X_NUM) AS SUM_DENIEDHDRSNOLINES1X_NUM,
SUM(DENIEDHDRSNOLINES1X_DEN) AS SUM_DENIEDHDRSNOLINES1X_DEN,
SUM(PAIDHDRSNONONDENIEDLINES1X_NUM) AS SUM_PAIDHDRSNONONDENIEDLINES1X_NUM,
SUM(PAIDHDRSNONONDENIEDLINES1X_DEN) AS SUM_PAIDHDRSNONONDENIEDLINES1X_DEN,
SUM(FROMSERVICEDATE1X_NUM) AS SUM_FROMSERVICEDATE1X_NUM,
SUM(FROMSERVICEDATE1X_DEN) AS SUM_FROMSERVICEDATE1X_DEN,
SUM(TOSERVICEDATE1X_NUM) AS SUM_TOSERVICEDATE1X_NUM,
SUM(TOSERVICEDATE1X_DEN) AS SUM_TOSERVICEDATE1X_DEN,
SUM(PRESCRIPTIONFILLDATE1X_NUM) AS SUM_PRESCRIPTIONFILLDATE1X_NUM,
SUM(PRESCRIPTIONFILLDATE1X_DEN) AS SUM_PRESCRIPTIONFILLDATE1X_DEN,
SUM(BILLINGPROVIDERNPI1X_NUM) AS SUM_BILLINGPROVIDERNPI1X_NUM,
SUM(BILLINGPROVIDERNPI1X_DEN) AS SUM_BILLINGPROVIDERNPI1X_DEN,
SUM(BILLINGPROVIDERINTERNALID1X_NUM) AS SUM_BILLINGPROVIDERINTERNALID1X_NUM,
SUM(BILLINGPROVIDERINTERNALID1X_DEN) AS SUM_BILLINGPROVIDERINTERNALID1X_DEN,
SUM(CLAIMBILLEDAMOUNT1X_NUM) AS SUM_CLAIMBILLEDAMOUNT1X_NUM,
SUM(CLAIMBILLEDAMOUNT1X_DEN) AS SUM_CLAIMBILLEDAMOUNT1X_DEN,
SUM(ACCOMREVENUECODE1X_NUM) AS SUM_ACCOMREVENUECODE1X_NUM,
SUM(ACCOMREVENUECODE1X_DEN) AS SUM_ACCOMREVENUECODE1X_DEN,
SUM(AMTPAIDMCARESCHIP1X_NUM) AS SUM_AMTPAIDMCARESCHIP1X_NUM,
SUM(AMTPAIDMCARESCHIP1X_DEN) AS SUM_AMTPAIDMCARESCHIP1X_DEN,
SUM(AMTPAIDMCAREMEDICAID1X_NUM) AS SUM_AMTPAIDMCAREMEDICAID1X_NUM,
SUM(AMTPAIDMCAREMEDICAID1X_DEN) AS SUM_AMTPAIDMCAREMEDICAID1X_DEN,
SUM(AMTPAIDMCAREHDRLTXOVER1X_NUM) AS SUM_AMTPAIDMCAREHDRLTXOVER1X_NUM,
SUM(AMTPAIDMCAREHDRLTXOVER1X_DEN) AS SUM_AMTPAIDMCAREHDRLTXOVER1X_DEN,
SUM(AMTPAIDCODEDMCAREHDRXOVER1X_NUM) AS SUM_AMTPAIDCODEDMCAREHDRXOVER1X_NUM,
SUM(AMTPAIDCODEDMCAREHDRXOVER1X_DEN) AS SUM_AMTPAIDCODEDMCAREHDRXOVER1X_DEN,
SUM(AMTPAIDCODEDMCAREHDRNONXOVER1X_NUM) AS SUM_AMTPAIDCODEDMCAREHDRNONXOVER1X_NUM,
SUM(AMTPAIDCODEDMCAREHDRNONXOVER1X_DEN) AS SUM_AMTPAIDCODEDMCAREHDRNONXOVER1X_DEN,
SUM(ANCILLARYCODE1X_NUM) AS SUM_ANCILLARYCODE1X_NUM,
SUM(ANCILLARYCODE1X_DEN) AS SUM_ANCILLARYCODE1X_DEN,
SUM(ATTENDINGPROVIDERINTERNALID1X_NUM) AS SUM_ATTENDINGPROVIDERINTERNALID1X_NUM,
SUM(ATTENDINGPROVIDERINTERNALID1X_DEN) AS SUM_ATTENDINGPROVIDERINTERNALID1X_DEN,
SUM(ATTENDINGPROVIDERNPI1X_NUM) AS SUM_ATTENDINGPROVIDERNPI1X_NUM,
SUM(ATTENDINGPROVIDERNPI1X_DEN) AS SUM_ATTENDINGPROVIDERNPI1X_DEN,
SUM(TYPEOFADMISSION1X_NUM) AS SUM_TYPEOFADMISSION1X_NUM,
SUM(TYPEOFADMISSION1X_DEN) AS SUM_TYPEOFADMISSION1X_DEN,
SUM(BILLINGPROVIDERTAXONOMY1X_NUM) AS SUM_BILLINGPROVIDERTAXONOMY1X_NUM,
SUM(BILLINGPROVIDERTAXONOMY1X_DEN) AS SUM_BILLINGPROVIDERTAXONOMY1X_DEN,
SUM(BILLINGPROVIDERTYPE1X_NUM) AS SUM_BILLINGPROVIDERTYPE1X_NUM,
SUM(BILLINGPROVIDERTYPE1X_DEN) AS SUM_BILLINGPROVIDERTYPE1X_DEN,
SUM(BRANDGENERICIND1X_NUM) AS SUM_BRANDGENERICIND1X_NUM,
SUM(BRANDGENERICIND1X_DEN) AS SUM_BRANDGENERICIND1X_DEN,
SUM(COMPOUNDDRUGIND1X_NUM) AS SUM_COMPOUNDDRUGIND1X_NUM,
SUM(COMPOUNDDRUGIND1X_DEN) AS SUM_COMPOUNDDRUGIND1X_DEN,
SUM(MEDICAIDCOVINPATIENTDAYS1X_NUM) AS SUM_MEDICAIDCOVINPATIENTDAYS1X_NUM,
SUM(MEDICAIDCOVINPATIENTDAYS1X_DEN) AS SUM_MEDICAIDCOVINPATIENTDAYS1X_DEN,
SUM(PRESCRIBINGPROVIDERINTERNALID1X_NUM) AS SUM_PRESCRIBINGPROVIDERINTERNALID1X_NUM,
SUM(PRESCRIBINGPROVIDERINTERNALID1X_DEN) AS SUM_PRESCRIBINGPROVIDERINTERNALID1X_DEN,
SUM(PRESCRIBINGPROVIDERNPI1X_NUM) AS SUM_PRESCRIBINGPROVIDERNPI1X_NUM,
SUM(PRESCRIBINGPROVIDERNPI1X_DEN) AS SUM_PRESCRIBINGPROVIDERNPI1X_DEN,
SUM(REBATEELIGIBLEIND1X_NUM) AS SUM_REBATEELIGIBLEIND1X_NUM,
SUM(REBATEELIGIBLEIND1X_DEN) AS SUM_REBATEELIGIBLEIND1X_DEN,
SUM(REFERRINGPROVIDERINTERNALID1X_NUM) AS SUM_REFERRINGPROVIDERINTERNALID1X_NUM,
SUM(REFERRINGPROVIDERINTERNALID1X_DEN) AS SUM_REFERRINGPROVIDERINTERNALID1X_DEN,
SUM(REFERRINGPROVIDERNPI1X_NUM) AS SUM_REFERRINGPROVIDERNPI1X_NUM,
SUM(REFERRINGPROVIDERNPI1X_DEN) AS SUM_REFERRINGPROVIDERNPI1X_DEN,
SUM(SERVICINGPROVIDERINTERNALID1X_NUM) AS SUM_SERVICINGPROVIDERINTERNALID1X_NUM,
SUM(SERVICINGPROVIDERINTERNALID1X_DEN) AS SUM_SERVICINGPROVIDERINTERNALID1X_DEN,
SUM(CLAIMALLOWABLEAMOUNT1X_NUM) AS SUM_CLAIMALLOWABLEAMOUNT1X_NUM,
SUM(CLAIMALLOWABLEAMOUNT1X_DEN) AS SUM_CLAIMALLOWABLEAMOUNT1X_DEN,
SUM(INPAT_HDR) SUM_INPAT_HDR,
SUM(OUTPAT_HDR) SUM_OUTPAT_HDR ,
SUM(LTC_HDR) SUM_LTC_HDR ,
SUM(PROF_HDR) SUM_PROF_HDR ,
SUM(HOME_HDR) SUM_HOME_HDR ,
SUM(DENT_HDR) SUM_DENT_HDR ,
SUM(PHARM_HDR) SUM_PHARM_HDR ,
SUM(COMPOUND_HDR) SUM_COMPOUND_HDR ,
SUM(NON_PHARM_HDR) SUM_NON_PHARM_HDR ,
SUM(IP_OA_NX_P) SUM_IP_OA_NX_P ,
SUM(IP_O_NX_P) SUM_IP_O_NX_P ,
SUM(IP_OA_P) SUM_IP_OA_P ,
SUM(LT_O_X_P) SUM_LT_O_X_P ,
SUM(IPLT_O_NX_P) SUM_IPLT_O_NX_P ,
SUM(OT_OA_P) SUM_OT_OA_P ,
SUM(IPLTOT_OA_NX_P) SUM_IPLTOT_OA_NX_P ,
SUM(IPLTOT_OA_P) SUM_IPLTOT_OA_P ,
SUM(RX_OA_NX_P) SUM_RX_OA_NX_P ,
SUM(RX_OA_P) SUM_RX_OA_P ,
SUM(Q_OA_P) SUM_Q_OA_P ,
SUM(IPLTRX_OA_P) SUM_IPLTRX_OA_P ,
SUM(IPOTRX_OA_P) SUM_IPOTRX_OA_P ,
SUM(IPLTOTRX_OA_P) SUM_IPLTOTRX_OA_P ,
SUM(IPLTOTRX_D) SUM_IPLTOTRX_D ,
SUM(IPLTOTRX_OA_NX_P) SUM_IPLTOTRX_OA_NX_P ,
SUM(TOT_REX_HDR) SUM_TOT_REX_HDR 
FROM (

SELECT
RUN_DATE,
CDE_ENC_MCO,
claim_type,
cde_clm_status,
cde_clm_disposition,
ind_crossover,

CASE WHEN PATIENTSTATUSCODE1X = 'VALID' THEN 1 ELSE 0 END PATIENTSTATUSCODE1X_NUM,
CASE WHEN PATIENTSTATUSCODE1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END PATIENTSTATUSCODE1X_DEN,

CASE WHEN MEMBERID1X  = 'VALID' THEN 1 ELSE 0 END MEMBERID1X_NUM,
CASE WHEN MEMBERID1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END MEMBERID1X_DEN,

CASE WHEN ADJUDICATIONDATEHDRX  = 'VALID' THEN 1 ELSE 0 END ADJUDICATIONDATEHDRX_NUM,
CASE WHEN ADJUDICATIONDATEHDRX IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END ADJUDICATIONDATEHDRX_DEN,

CASE WHEN ADJUDICATIONDATEDTLX = 'VALID' THEN 1 ELSE 0 END ADJUDICATIONDATEDTLX_NUM,
CASE WHEN ADJUDICATIONDATEDTLX IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END ADJUDICATIONDATEDTLX_DEN,

CASE WHEN PAIDHDRSNOLINES1X = 'VALID' THEN 1 ELSE 0 END PAIDHDRSNOLINES1X_NUM,
CASE WHEN PAIDHDRSNOLINES1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END PAIDHDRSNOLINES1X_DEN,

CASE WHEN DENIEDHDRSNOLINES1X = 'VALID' THEN 1 ELSE 0 END DENIEDHDRSNOLINES1X_NUM,
CASE WHEN DENIEDHDRSNOLINES1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END DENIEDHDRSNOLINES1X_DEN,

CASE WHEN PAIDHDRSNONONDENIEDLINES1X = 'VALID' THEN 1 ELSE 0 END PAIDHDRSNONONDENIEDLINES1X_NUM,
CASE WHEN PAIDHDRSNONONDENIEDLINES1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END PAIDHDRSNONONDENIEDLINES1X_DEN,

CASE WHEN FROMSERVICEDATE1X = 'VALID' THEN 1 ELSE 0 END FROMSERVICEDATE1X_NUM,
CASE WHEN FROMSERVICEDATE1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END FROMSERVICEDATE1X_DEN,

CASE WHEN TOSERVICEDATE1X = 'VALID' THEN 1 ELSE 0 END TOSERVICEDATE1X_NUM,
CASE WHEN TOSERVICEDATE1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END TOSERVICEDATE1X_DEN,

CASE WHEN PRESCRIPTIONFILLDATE1X = 'VALID' THEN 1 ELSE 0 END PRESCRIPTIONFILLDATE1X_NUM,
CASE WHEN PRESCRIPTIONFILLDATE1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END PRESCRIPTIONFILLDATE1X_DEN,

CASE WHEN BILLINGPROVIDERNPI1X = 'VALID' THEN 1 ELSE 0 END BILLINGPROVIDERNPI1X_NUM,
CASE WHEN BILLINGPROVIDERNPI1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END BILLINGPROVIDERNPI1X_DEN,

CASE WHEN BILLINGPROVIDERINTERNALID1X = 'VALID' THEN 1 ELSE 0 END BILLINGPROVIDERINTERNALID1X_NUM,
CASE WHEN BILLINGPROVIDERINTERNALID1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END BILLINGPROVIDERINTERNALID1X_DEN,

CASE WHEN CLAIMBILLEDAMOUNT1X = 'VALID' THEN 1 ELSE 0 END CLAIMBILLEDAMOUNT1X_NUM,
CASE WHEN CLAIMBILLEDAMOUNT1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END CLAIMBILLEDAMOUNT1X_DEN,

CASE WHEN ACCOMREVENUECODE1X = 'VALID' THEN 1 ELSE 0 END ACCOMREVENUECODE1X_NUM,
CASE WHEN ACCOMREVENUECODE1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END ACCOMREVENUECODE1X_DEN,

CASE WHEN AMTPAIDMCARESCHIP1X = 'VALID' THEN 1 ELSE 0 END AMTPAIDMCARESCHIP1X_NUM,
CASE WHEN AMTPAIDMCARESCHIP1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END AMTPAIDMCARESCHIP1X_DEN,

CASE WHEN AMTPAIDMCAREMEDICAID1X = 'VALID' THEN 1 ELSE 0 END AMTPAIDMCAREMEDICAID1X_NUM,
CASE WHEN AMTPAIDMCAREMEDICAID1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END AMTPAIDMCAREMEDICAID1X_DEN,

CASE WHEN AMTPAIDMCAREHDRLTXOVER1X = 'VALID' THEN 1 ELSE 0 END AMTPAIDMCAREHDRLTXOVER1X_NUM,
CASE WHEN AMTPAIDMCAREHDRLTXOVER1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END AMTPAIDMCAREHDRLTXOVER1X_DEN,

CASE WHEN AMTPAIDCODEDMCAREHDRXOVER1X = 'VALID' THEN 1 ELSE 0 END AMTPAIDCODEDMCAREHDRXOVER1X_NUM,
CASE WHEN AMTPAIDCODEDMCAREHDRXOVER1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END AMTPAIDCODEDMCAREHDRXOVER1X_DEN,

CASE WHEN AMTPAIDCODEDMCAREHDRNONXOVER1X = 'VALID' THEN 1 ELSE 0 END AMTPAIDCODEDMCAREHDRNONXOVER1X_NUM,
CASE WHEN AMTPAIDCODEDMCAREHDRNONXOVER1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END AMTPAIDCODEDMCAREHDRNONXOVER1X_DEN,

CASE WHEN ANCILLARYCODE1X = 'VALID' THEN 1 ELSE 0 END ANCILLARYCODE1X_NUM,
CASE WHEN ANCILLARYCODE1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END ANCILLARYCODE1X_DEN,

CASE WHEN ATTENDINGPROVIDERINTERNALID1X = 'VALID' THEN 1 ELSE 0 END ATTENDINGPROVIDERINTERNALID1X_NUM,
CASE WHEN ATTENDINGPROVIDERINTERNALID1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END ATTENDINGPROVIDERINTERNALID1X_DEN,

CASE WHEN ATTENDINGPROVIDERNPI1X = 'VALID' THEN 1 ELSE 0 END ATTENDINGPROVIDERNPI1X_NUM,
CASE WHEN ATTENDINGPROVIDERNPI1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END ATTENDINGPROVIDERNPI1X_DEN,

CASE WHEN TYPEOFADMISSION1X = 'VALID' THEN 1 ELSE 0 END TYPEOFADMISSION1X_NUM,
CASE WHEN TYPEOFADMISSION1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END TYPEOFADMISSION1X_DEN,

CASE WHEN BILLINGPROVIDERTAXONOMY1X = 'VALID' THEN 1 ELSE 0 END BILLINGPROVIDERTAXONOMY1X_NUM,
CASE WHEN BILLINGPROVIDERTAXONOMY1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END BILLINGPROVIDERTAXONOMY1X_DEN,

CASE WHEN BILLINGPROVIDERTYPE1X = 'VALID' THEN 1 ELSE 0 END BILLINGPROVIDERTYPE1X_NUM,
CASE WHEN BILLINGPROVIDERTYPE1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END BILLINGPROVIDERTYPE1X_DEN,

CASE WHEN BRANDGENERICIND1X = 'VALID' THEN 1 ELSE 0 END BRANDGENERICIND1X_NUM,
CASE WHEN BRANDGENERICIND1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END BRANDGENERICIND1X_DEN,

CASE WHEN COMPOUNDDRUGIND1X = 'VALID' THEN 1 ELSE 0 END COMPOUNDDRUGIND1X_NUM,
CASE WHEN COMPOUNDDRUGIND1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END COMPOUNDDRUGIND1X_DEN,

CASE WHEN MEDICAIDCOVINPATIENTDAYS1X = 'VALID' THEN 1 ELSE 0 END MEDICAIDCOVINPATIENTDAYS1X_NUM,
CASE WHEN MEDICAIDCOVINPATIENTDAYS1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END MEDICAIDCOVINPATIENTDAYS1X_DEN,

CASE WHEN PRESCRIBINGPROVIDERINTERNALID1X = 'VALID' THEN 1 ELSE 0 END PRESCRIBINGPROVIDERINTERNALID1X_NUM,
CASE WHEN PRESCRIBINGPROVIDERINTERNALID1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END PRESCRIBINGPROVIDERINTERNALID1X_DEN,

CASE WHEN PRESCRIBINGPROVIDERNPI1X = 'VALID' THEN 1 ELSE 0 END PRESCRIBINGPROVIDERNPI1X_NUM,
CASE WHEN PRESCRIBINGPROVIDERNPI1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END PRESCRIBINGPROVIDERNPI1X_DEN,

CASE WHEN REBATEELIGIBLEIND1X = 'VALID' THEN 1 ELSE 0 END REBATEELIGIBLEIND1X_NUM,
CASE WHEN REBATEELIGIBLEIND1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END REBATEELIGIBLEIND1X_DEN,

CASE WHEN REFERRINGPROVIDERINTERNALID1X = 'VALID' THEN 1 ELSE 0 END REFERRINGPROVIDERINTERNALID1X_NUM,
CASE WHEN REFERRINGPROVIDERINTERNALID1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END REFERRINGPROVIDERINTERNALID1X_DEN,

CASE WHEN REFERRINGPROVIDERNPI1X = 'VALID' THEN 1 ELSE 0 END REFERRINGPROVIDERNPI1X_NUM,
CASE WHEN REFERRINGPROVIDERNPI1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END REFERRINGPROVIDERNPI1X_DEN,

CASE WHEN SERVICINGPROVIDERINTERNALID1X = 'VALID' THEN 1 ELSE 0 END SERVICINGPROVIDERINTERNALID1X_NUM,
CASE WHEN SERVICINGPROVIDERINTERNALID1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END SERVICINGPROVIDERINTERNALID1X_DEN,

CASE WHEN CLAIMALLOWABLEAMOUNT1X = 'VALID' THEN 1 ELSE 0 END CLAIMALLOWABLEAMOUNT1X_NUM,
CASE WHEN CLAIMALLOWABLEAMOUNT1X IN ('VALID','INVALID','NULL')  THEN 1 ELSE 0 END CLAIMALLOWABLEAMOUNT1X_DEN,
INPAT_HDR,
OUTPAT_HDR,
LTC_HDR,
PROF_HDR,
HOME_HDR,
DENT_HDR,
PHARM_HDR,
COMPOUND_HDR,
NON_PHARM_HDR,
IP_OA_NX_P,
IP_O_NX_P,
IP_OA_P,
LT_O_X_P,
IPLT_O_NX_P,
OT_OA_P,
IPLTOT_OA_NX_P,
IPLTOT_OA_P,
RX_OA_NX_P,
RX_OA_P,
Q_OA_P,
IPLTRX_OA_P,
IPOTRX_OA_P,
IPLTOTRX_OA_P,
IPLTOTRX_D,
IPLTOTRX_OA_NX_P,
TOT_REX_HDR 
FROM MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_837_HDR_wrk1
)
GROUP BY RUN_DATE, CDE_ENC_MCO, 
claim_type,
cde_clm_status,
cde_clm_disposition,
ind_crossover
ORDER BY RUN_DATE, CDE_ENC_MCO,
claim_type,
cde_clm_status,
cde_clm_disposition,
ind_crossover

)
where cde_clm_status = 'P' 
and cde_clm_disposition in ('O','A')

ORDER BY RUN_DATE, CDE_ENC_MCO,
claim_type,
cde_clm_status,
cde_clm_disposition,
ind_crossover

;

----------------

SELECT
RUN_DATE,
CDE_ENC_MCO,
claim_type,
cde_clm_status,
cde_clm_disposition,
ind_crossover,
SUM(INPAT_HDR) SUM_INPAT_HDR,
SUM(OUTPAT_HDR) SUM_OUTPAT_HDR ,
SUM(LTC_HDR) SUM_LTC_HDR ,
SUM(PROF_HDR) SUM_PROF_HDR ,
SUM(HOME_HDR) SUM_HOME_HDR ,
SUM(DENT_HDR) SUM_DENT_HDR ,
SUM(PHARM_HDR) SUM_PHARM_HDR ,
SUM(COMPOUND_HDR) SUM_COMPOUND_HDR ,
SUM(NON_PHARM_HDR) SUM_NON_PHARM_HDR ,
SUM(IP_OA_NX_P) SUM_IP_OA_NX_P ,
SUM(IP_O_NX_P) SUM_IP_O_NX_P ,
SUM(IP_OA_P) SUM_IP_OA_P ,
SUM(LT_O_X_P) SUM_LT_O_X_P ,
SUM(IPLT_O_NX_P) SUM_IPLT_O_NX_P ,
SUM(OT_OA_P) SUM_OT_OA_P ,
SUM(IPLTOT_OA_NX_P) SUM_IPLTOT_OA_NX_P ,
SUM(IPLTOT_OA_P) SUM_IPLTOT_OA_P ,
SUM(RX_OA_NX_P) SUM_RX_OA_NX_P ,
SUM(RX_OA_P) SUM_RX_OA_P ,
SUM(Q_OA_P) SUM_Q_OA_P ,
SUM(IPLTRX_OA_P) SUM_IPLTRX_OA_P ,
SUM(IPOTRX_OA_P) SUM_IPOTRX_OA_P ,
SUM(IPLTOTRX_OA_P) SUM_IPLTOTRX_OA_P ,
SUM(IPLTOTRX_D) SUM_IPLTOTRX_D ,
SUM(IPLTOTRX_OA_NX_P) SUM_IPLTOTRX_OA_NX_P ,
SUM(TOT_REX_HDR) SUM_TOT_REX_HDR 
FROM MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_837_HDR_wrk1
GROUP BY RUN_DATE, CDE_ENC_MCO, 
claim_type,
cde_clm_status,
cde_clm_disposition,
ind_crossover
ORDER BY RUN_DATE, CDE_ENC_MCO,
claim_type,
cde_clm_status,
cde_clm_disposition,
ind_crossover
;

select *
from MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_837_HDR_wrk1
limit 10;

DROP TABLE MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_837_HDR_wrk1;

CREATE TABLE MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_837_HDR_wrk1 AS

--TRUNCATE TABLE MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_837_HDR_wrk1;

--INSERT INTO MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_837_HDR_wrk1
SELECT DISTINCT
    RUN_DATE,
    CLAIM_LEG_TYPE,
    NUM_ICN_HDR AS NUM_ICN,
    CDE_ENTITY_MODEL,
    CDE_ENC_MCO,
    CDE_ENC_ACO,
    ID_SUBMITTER,
    DOS_FROM_DT,
    Claim_Type,
    CDE_CLM_STATUS,
    CDE_CLM_DISPOSITION,
    IND_CROSSOVER,
    WH_FROM_DT,
    MD_BATCH_SEQ,


/*
2.001.31	Measure	Critical	 % of claims for which Patient Status is NOT 'still a patient' but are missing Discharge Date	5%	
IP	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Non-Crossover, Paid Claims- claims missing Discharge Date and Patient Status is NOT 'still a patient' 	IN SENDPRO TARGET DASHBOARD

"Patient status should not  = 30 (still a patient) or be missing
MA use the national standard Patient status. No cross walk needed. "	A code indicating the Patients status as of the ENDING-DATE-OF-SERVICE. Values used are from UB-04. This is also referred to as DISCHARGE-STATUS.

from SCO
case when Claim_Type IN('I','O') AND cde_patient_status not in ('+', '-', ' ') then 1 else 0 end as CDE_PATIENT_STATUS1,
case when (Claim_Type='I' AND substr(cde_type_of_bill_enc,1,2) <> '21' and SUBSTR(DSC_PATIENT_STATUS,1,2) NOT BETWEEN '30' AND '39')
AND (MX.DISCHARGE_DT IS NOT NULL and discharge_dt >= admit_dt) THEN 1 else 0 end DISCHARGE_DT1,

?? showuld we be using just 1 or 0 for valid/invalid or should we do VALID/INVALID/NOT APP/NULL ?

*/
/*
-- DI
    CASE WHEN Claim_Type IN ('I')
    AND CDE_CLM_DISPOSITION IN ('O','A')
    AND IND_CROSSOVER = 'N'
    AND CDE_CLM_STATUS = 'P'
	AND PatientStatusCode IS NOT NULL
	AND PatientStatusCode NOT IN ('#','+','-')
    AND PatientStatusCode IN (SELECT CDE_CHAR FROM MHDWQA.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_PATIENT_STATUS' AND CDE_CHAR NOT IN ('#','**','+','-','$','  '))
    AND PatientStatusCode <> '30' -- STILL PATIENT
    AND (DISCHARGE_DT IS NOT NULL and DISCHARGE_DT >= ADMIT_DT)
        THEN 1 ELSE 0 END PatientStatusCode1,
*/
--  Ex
    CASE WHEN Claim_Type NOT IN ('I') 
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
        WHEN PatientStatusCode IS NULL OR PatientStatusCode IN ('#','+','-') THEN 'NULL'
        WHEN PatientStatusCode NOT IN (SELECT CDE_CHAR FROM MHDWQA.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_PATIENT_STATUS' 
            AND CDE_CHAR NOT IN ('#','**','+','-','$','  '))
        THEN 'NULL'
        WHEN (PatientStatusCode <> '30') AND (DISCHARGE_DT IS NULL OR DISCHARGE_DT < ADMIT_DT) THEN 'INVALID'
        ELSE 'VALID'
    END AS PatientStatusCode1X,

/*
2.001.32	Measure	Critical	 % missing: MSIS-IDENTIFICATION-NUM	2%	
"IP LT OT RX"	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Non-Crossover, Paid Claims - claims missing: MSIS-IDENTIFICATION-NUM	SIMILAR IN SENDPRO TARGET DASHBOARD
*/

    CASE WHEN Claim_Type NOT IN ('I','O','M','L','H','D','P','Q') 
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
        WHEN (FACT_MEM_SEQ IS NULL OR FACT_MEM_SEQ IN (-1,-4,-5))  THEN 'NULL'
        WHEN FACT_MEM_SEQ <= 0 THEN 'INVALID'
		WHEN  (
              ( NOT EXISTS (SELECT ID_MEDICAID from MHDWQA.NW.NW_MEMBER mem WHERE FACT_MEM_SEQ = mem.MEM_SEQ AND ID_MEDICAID NOT IN ('#','+','-',' ')) ) 
             )
        THEN 'INVALID'
        ELSE 'VALID'
    END AS MemberID1X,

/*
2.001.33	Measure	Critical	% of claim lines with no corresponding claim header	0%	
"IP LT OT RX"	
This measure should show % of Medicaid and S-CHIP Encounters, Original and Replacement, Non-Crossover, Paid Claims - claim lines with no corresponding claim header	Rima to check but this might be fixed with SendPro structure

?? this is not at the claim line level... we are at the claim level with line details joined in... so we can just see if there are any lines without a header... 
if there is no header there will be no rows returned

DTL Processing

    CASE WHEN Claim_Type NOT IN ('I','O','M','L','P') 
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
    THEN 'NOT APP'


select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
RIGHT JOIN MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
    ON inst.NUM_ICN = dtl.NUM_ICN
WHERE inst.NUM_ICN IS NULL;

select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
WHERE NOT EXISTS (
    SELECT inst.NUM_ICN 
    FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
    WHERE inst.NUM_ICN = dtl.NUM_ICN
);

*/


/*
2.001.36	Measure	Critical	 % of claim header record segments missing ADJUDICATION-DATE	0%	
"IP LT OT RX"	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Non-Crossover, Paid Claim, 
claim header record segments missing ADJUDICATION-DATE	
Record segment just references the line, header or other segment table used. So this just means claim headers.

we actually use the WH_FROM_DT

*/

    CASE WHEN Claim_Type NOT IN ('I','L','O','M','H','D','P','Q') 
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
        WHEN (WH_FROM_DT IS NULL) THEN 'NULL'
        WHEN (WH_FROM_DT = '1900-01-01') THEN 'INVALID'
        ELSE 'VALID'
    END AS AdjudicationDateHdrX,

/*
2.001.37	Measure	Critical	% of claim line record segments missing ADJUDICATION-DATE	0%	
"IP LT OT RX"	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Non-Crossover, Paid Claims, claim line record segments missing ADJUDICATION-DATE	"
JPR - We should dicuss.  I was thinking keep at month level. Also, there are too many metrics so we need a rollup dashboard that can be drill in to the measure by priority.  
See Moch Up Sheet.
Record segment just references the line, header or other segment table used. So this just means claim headers."

we actually use the WH_FROM_DT
added DTL_WH_FROM_DT

DTL Processing
-- this is headers with detail invlaid lines

    CASE WHEN Claim_Type NOT IN ('I','L','O','M','H','D','P','Q') 
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
        WHEN (DTL_WH_FROM_DT IS NULL AND DTL_WH_FROM_DT IS NULL) THEN 'NULL'
        WHEN (DTL_WH_FROM_DT = '1900-01-01' AND DTL_WH_FROM_DT = '1900-01-01') THEN 'INVALID'
        ELSE 'VALID'
    END AS AdjudicationDateDtlX,   


*/

    CASE WHEN Claim_Type NOT IN ('I','L','O','M','H','D','P','Q') 
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

        WHEN  CLAIM_LEG_TYPE = 'INST'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN AND (dtl.WH_FROM_DT IS NULL OR dtl.WH_FROM_DT = '1900-01-01'))   
        THEN 'INVALID'
        WHEN  CLAIM_LEG_TYPE = 'PROF'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_PROF_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN AND (dtl.WH_FROM_DT IS NULL OR dtl.WH_FROM_DT = '1900-01-01'))
        THEN 'INVALID'
        WHEN  CLAIM_LEG_TYPE = 'DNTL'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_DNTL_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN AND (dtl.WH_FROM_DT IS NULL OR dtl.WH_FROM_DT = '1900-01-01'))
        THEN 'INVALID'
        WHEN  CLAIM_LEG_TYPE = 'PHRM'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_PHRM_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN AND (dtl.WH_FROM_DT IS NULL OR dtl.WH_FROM_DT = '1900-01-01'))
        THEN 'INVALID'
        ELSE 'VALID' 
    END AS AdjudicationDateDtlX,


/*
2.001.38	Measure	Critical	 % of claim headers that have no corresponding claim lines	0%	
"IP LT OT RX"	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Non-Crossover, Paid Claims, claim headers that have no corresponding claim lines	Define this in regards to SendPro and exceptions

select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
LEFT JOIN MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
    ON inst.NUM_ICN = dtl.NUM_ICN
WHERE dtl.NUM_ICN IS NULL;

select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
WHERE NOT EXISTS (
    SELECT dtl.NUM_ICN 
    FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
    WHERE inst.NUM_ICN = dtl.NUM_ICN
);

DTL Processing

*/

    CASE WHEN Claim_Type NOT IN ('I','L','O','M','H','D','P','Q') 
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

        WHEN  CLAIM_LEG_TYPE = 'INST'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN)
        THEN 'INVALID'
        WHEN  CLAIM_LEG_TYPE = 'PROF'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_PROF_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN)
        THEN 'INVALID'
        WHEN  CLAIM_LEG_TYPE = 'DNTL'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_DNTL_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN)
        THEN 'INVALID'
        WHEN  CLAIM_LEG_TYPE = 'PHRM'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_PHRM_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN)
        THEN 'INVALID'
        ELSE 'VALID' 
    END AS PaidHdrsNoLines1X,

/*
2.001.39	Measure	Critical	 % of denied claim headers that have no corresponding claim lines	0%	
"IP LT OT RX"	
This measure should show % of denied claim headers that have no corresponding claim lines	Define this in regards to SendPro and exceptions

select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
WHERE CDE_CLM_STATUS = 'D';

select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
LEFT JOIN MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
    ON inst.NUM_ICN = dtl.NUM_ICN
WHERE dtl.NUM_ICN IS NULL
AND inst.CDE_CLM_STATUS = 'D';

select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
WHERE NOT EXISTS (
    SELECT dtl.NUM_ICN 
    FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
    WHERE inst.NUM_ICN = dtl.NUM_ICN
)
AND inst.CDE_CLM_STATUS = 'D';

DTL Processing

*/


    CASE WHEN Claim_Type NOT IN ('I','L','O','M','H','D','P','Q') 
--        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
--        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'D'
        THEN 'NOT APP'

        WHEN  CLAIM_LEG_TYPE = 'INST'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN)
        THEN 'INVALID'
        WHEN  CLAIM_LEG_TYPE = 'PROF'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_PROF_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN)
        THEN 'INVALID'
        WHEN  CLAIM_LEG_TYPE = 'DNTL'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_DNTL_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN)
        THEN 'INVALID'
        WHEN  CLAIM_LEG_TYPE = 'PHRM'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_PHRM_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN)
        THEN 'INVALID'
        ELSE 'VALID' 
    END AS DeniedHdrsNoLines1X,

/*
2.001.40	Measure	Critical	 % of denied claim lines that have no corresponding claim header	0%	
"IP LT OT RX"	
This measure should show % of denied claim lines that have no corresponding claim header	Define this in regards to SendPro and exceptions

select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
WHERE CDE_CLM_STATUS = 'D';

select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
RIGHT JOIN MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
    ON inst.NUM_ICN = dtl.NUM_ICN
WHERE inst.NUM_ICN IS NULL
AND dtl.CDE_CLM_STATUS = 'D';

select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
WHERE NOT EXISTS (
    SELECT inst.NUM_ICN 
    FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
    WHERE inst.NUM_ICN = dtl.NUM_ICN
)
AND dtl.CDE_CLM_STATUS = 'D';

DTL Processing
*/


/*
2.001.41	Measure	Critical	 % of claim headers that have no corresponding non-denied claim lines	0%	
"IP LT OT RX"	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Non-Crossover, Paid Claims, claim headers that have no corresponding non-denied claim lines	Define this in regards to SendPro and exceptions

select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
WHERE CDE_CLM_STATUS != 'D';

select count(1)
FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
WHERE NOT EXISTS (
    SELECT dtl.NUM_ICN 
    FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
    WHERE inst.NUM_ICN = dtl.NUM_ICN
    AND dtl.CDE_CLM_STATUS != 'D'
);

-- validation

select *
from MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
where dtl.NUM_ICN in (

select inst.NUM_ICN
FROM MHDWQA.SENDPRO.SPRO_B_ENC_CLAIM_INST_LEG_HIST inst
WHERE NOT EXISTS (
    SELECT dtl.NUM_ICN 
    FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
    WHERE inst.NUM_ICN = dtl.NUM_ICN
    AND dtl.CDE_CLM_STATUS != 'D'
)

and dtl.CDE_CLM_STATUS != 'D'
);
DTL Processing

*/

    CASE WHEN Claim_Type NOT IN ('I','L','O','M','H','D','P','Q') 
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

        WHEN  CLAIM_LEG_TYPE = 'INST'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN and dtl.CDE_CLM_STATUS != 'D')
        THEN 'INVALID'
        WHEN  CLAIM_LEG_TYPE = 'PROF'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_PROF_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN and dtl.CDE_CLM_STATUS != 'D')
        THEN 'INVALID'
        WHEN  CLAIM_LEG_TYPE = 'DNTL'
              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_DNTL_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN and dtl.CDE_CLM_STATUS != 'D')
        THEN 'INVALID'
--        WHEN  CLAIM_LEG_TYPE = 'PHRM'
--              AND NOT EXISTS (SELECT dtl.NUM_DTL FROM MHDWQA.SENDPRO.SPRO_B_ENC_PHRM_INFO_DTL_HIST dtl WHERE NUM_ICN_HDR = dtl.NUM_ICN and dtl.CDE_CLM_STATUS != 'D')
--        THEN 'INVALID'
        ELSE 'VALID' 
    END AS PaidHdrsNoNonDeniedLines1X,


/*
2.001.42	Measure	Critical	 % of claims missing BEGINNING-DATE-OF-SERVICE	2%	
"LT IP OT"	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Non-Crossover, Paid Claims, claims missing BEGINNING-DATE-OF-SERVICE	

-- this is taken from Final
*/

    CASE WHEN Claim_Type NOT IN ('I','O','M','D','L','H') 
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
        WHEN DOS_FROM_DT IS NULL THEN 'NULL'
        WHEN DOS_FROM_DT = '1900-01-01' THEN 'INVALID'
        ELSE 'VALID'
    END AS FromServiceDate1X,

/*
2.001.43	Measure	Critical	 % of claims missing: ENDING-DATE-OF-SERVICE	2%	
"LT IP OT"	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Non-Crossover, Paid Claims, claims missing: ENDING-DATE-OF-SERVICE	

-- this is taken from Final
*/

    CASE WHEN Claim_Type NOT IN ('I','O','M','D','L','H') 
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
        WHEN DOS_TO_DT IS NULL THEN 'NULL'
        WHEN DOS_TO_DT = '1900-01-01' THEN 'INVALID'
        ELSE 'VALID'
    END AS ToServiceDate1X,


/*
2.001.44	Measure	Critical	 % of claims missing: PRESCRIPTION-FILL-DATE	2%	
RX	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Non-Crossover, Paid Claims, claims missing: PRESCRIPTION-FILL-DATE	

?? DTE_DISPENSE not in SPRO_B_ENC_CLAIM_PHRM_LEG_HIST
Suggest either using ADJUDICATION_DT or DOS_FROM_DT?

*/

    CASE WHEN Claim_Type NOT IN ('P','Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
        WHEN DOS_FROM_DT IS NULL THEN 'NULL'
        WHEN DOS_FROM_DT = '1900-01-01' THEN 'INVALID'
        ELSE 'VALID'
    END AS PrescriptionFillDate1X,


/*
2.001.01	Measure	High	 % of claim headers with Billing Provider NPI Number in an invalid format	<= 1%	
RX	
This measure should show the % of Medicaid and S-CHIP Encounter: Original and Adjustment, Paid Claims, claim headers with invalid formatting of Billing Provider NPI within.	
*/


    CASE WHEN Claim_Type NOT IN ('P','Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
-- 11/19/2025 - debugging

-- from Target
         WHEN 
         (
               (billing_ProviderNPI IS NULL OR billing_ProviderNPI IN ('#','+','-') OR billing_ProviderNPI IN ('0','000000000','0000000000') ) 
           
         )            
            THEN 'NULL'
		 WHEN 
         (
              (NOT EXISTS (SELECT ID_NPI from mhdwqa.SENDPRO.spro_b_enc_provider_hist where ID_NPI NOT IN ('#','+','-') AND ID_NPI = billing_ProviderNPI))
           
         )
         THEN 'INVALID'
--
         ELSE 'VALID' 
    END AS BillingProviderNPI1X,


/*
2.001.06	Measure	High	% missing: BILLING-PROV-NUM 	<= 2% missing	
"IP OT RX"	
This measure should show the % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing Billing Provider PID/SL.	

Final - Target
56	MPT_SENDPRO_ProviderPIDSL_Valid	Validity of  PIDSL is determined by performing a look up to the following tables 
    1.	SENDPRO.SPRO_B_ENC837_PROVIDER_HIST on the field ID_PROVIDER
    If valid then 1 else 0

?? Validate how this validates PIDSL
*/


    CASE WHEN Claim_Type NOT IN ('I','O','M','D','H','P','Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

-- from Target
--         WHEN (billing_ProviderInternalId IS NULL OR billing_ProviderInternalId IN ('#','+','-')) AND (dtl_billing_ProviderInternalId IS NULL OR dtl_billing_ProviderInternalId IN ('#','+','-')) THEN 'NULL'
--		 WHEN ( 
--               (NOT EXISTS (SELECT ENC_PROV_ID from mhdwqa.SENDPRO.spro_b_enc_provider_hist where ENC_PROV_ID NOT IN ('#','+','-') AND ENC_PROV_ID = billing_ProviderInternalId) )
--           AND (NOT EXISTS (SELECT ENC_PROV_ID from mhdwqa.SENDPRO.spro_b_enc_provider_hist where ENC_PROV_ID NOT IN ('#','+','-') AND ENC_PROV_ID = dtl_billing_ProviderInternalId) )
--         )
--         THEN 'INVALID'

-- Billing Internal Provider Address Location

-- 11/19/2025 - debugging
		 WHEN 
         (
             (NOT EXISTS (SELECT prv.ID_PROVIDER_LOCATION from mhdwqa.SENDPRO.spro_b_enc_provider_hist as prv
         where BILLING_ENC_PRV_SEQ = prv.ENC_PRV_SEQ AND prv.ID_PROVIDER_LOCATION IS NOT NULL AND prv.ID_PROVIDER_LOCATION NOT IN ('#','+','-')))

         )
         THEN 'INVALID'
 --

         ELSE 'VALID' 
    END AS BillingProviderInternalId1X,


/*
2.001.21	Measure	High	% missing: TOT-BILLED-AMT	<= 2% missing	
"IP LT RX"	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing Total Billed Amount	

from Dashboard Data Needed
The total amount should be the sum of each of the billed amounts submitted at the claim detail level.

If TYPE-OF-CLAIM = "4"(Medicaid or Medicaid-expansion Service Tracking Claim), then TOT-BILLED-AMT must = "00000000".
If TYPE-OF-CLAIM = 3, C, W (encounter record) this field should either be zero-filled or contain the amount paid by the plan to the provider. 

?? validating header AMT_BILLED = SUM of detail AMT_BILLED will require procesing at higher level of detail

?? TYPE-OF-CLAIM
?? If we assume that this is encounter record then the Target logic should be ok - except for header to detail check

This is the same as 05 aqnd 15
*/

    CASE WHEN Claim_Type NOT IN ('I','L','P','Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
-- from Target
    WHEN AMT_BILLED IS NULL THEN 'INVALID'
    WHEN AMT_BILLED <= 0 THEN 'INVALID'
    ELSE 'VALID'
END AS ClaimBilledAmount1X,


/*
2.001.22	Measure	High	% of claim headers with any accommodation revenue codes	>= 85% present	
IP	
This measure should show % of Medicaid Encounter: Original, Non-Crossover, Paid Claims, claim headers with Accomodation Rev Codes	

from Dashboard Data Needed
NW_B_REVENUE_CODE.CDE_REVENUE
Join on REV_SEQ from SPRO_B_ENC_INST_INFO_DTL_HIST
Accomodation Revenue Code Values = 100-219

from Target
24	MPT_SENDPRO_ServiceLineRevenueCode_Valid	If valid based on the lookup against the CDE_CHAR from NW_SUP_CODE_REF where CDE_GROUP='CDE_REVENUE'  then 1 else 0

?? This is at the claim header level but uses detail revenue codes... so if any detail line has a valid code then the header is valid? And needs to be aggregated.

Cant filter for only Medicaid at this time.
DTL Processing
*/

    CASE WHEN Claim_Type NOT IN ('I')
        OR CDE_CLM_DISPOSITION NOT IN ('O')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
        WHEN NOT EXISTS (SELECT rev.REV_SEQ 
                         FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
                              JOIN MHDWQA.NW.NW_B_REVENUE_CODE rev ON rev.REV_SEQ = dtl.REV_SEQ 
                        WHERE dtl.NUM_ICN = NUM_ICN_HDR
                        AND rev.CDE_REVENUE BETWEEN '100' AND '219')
        THEN 'INVALID'
    ELSE 'VALID'
    END AS AccomRevenueCode1X,

/*
2.001.23	Measure	High	% of claim headers with Total Medicaid Paid Amount = $0 or missing	<= 10% missing	
IP	
This measure should show % of S-CHIP Encounter: Original, Non-Crossover, Paid Claims, claim headers with Total Medicaid Paid Amount of $0 or are missing. 	

Cant filter for only S-CHIP at this time.

This is SCHIP
*/

    CASE WHEN Claim_Type NOT IN ('I','L')
        OR CDE_CLM_DISPOSITION NOT IN ('O')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
    WHEN AMT_PAID_MCARE IS NULL OR AMT_PAID_MCARE <= 0 THEN 'INVALID' 
    ELSE 'VALID'
    END AS AmtPaidMcareSChip1X,


/*
2.001.24	Measure	High	% of claim headers with Total Medicaid Paid Amount = $0 or missing	<= 10% missing	
IP	
This measure should show % of S-CHIP Encounter: Original, Non-Crossover, Paid Claims, claim headers with Total Medicaid Paid Amount of $0 or are missing. 	

?? Assuming this is for DTL, otherwise this is the same as 2.001.23

This is MEDICAID
*/

    CASE WHEN Claim_Type NOT IN ('I','L')
        OR CDE_CLM_DISPOSITION NOT IN ('O')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
    WHEN AMT_PAID_MCARE IS NULL OR AMT_PAID_MCARE <= 0 THEN 'INVALID' 
    ELSE 'VALID'
    END AS AmtPaidMcareMedicaid1X,


/*
2.001.25	Measure	High	% of claim headers with Total Medicaid Paid Amount = $0 or missing - non-Crossover Paid claims	<= 10% missing	
LT 	
This measure should show % of Medicaid Encounter: Original, non-Crossover, Paid Claims, claim headers with Total Medicaid Paid Amount of $0 or are missing.	

?? same as 23 but for LT - adding LT to 23
*/


/*
2.001.26	Measure	High	% of claim headers with Total Medicaid Paid Amount = $0 or missing - Crossover Paid claims	<= 40% missing	
LT 	
This measure should show % of Medicaid Encounter: Original, Crossover, Paid Claims, claim headers with Total Medicaid Paid Amount of $0 or are missing.	

LT Crossover
*/

    CASE WHEN Claim_Type NOT IN ('L')
        OR CDE_CLM_DISPOSITION NOT IN ('O')
        OR IND_CROSSOVER = 'N'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
    WHEN AMT_PAID_MCARE IS NULL OR AMT_PAID_MCARE <= 0 THEN 'INVALID' 
    ELSE 'VALID'
    END AS AmtPaidMcareHdrLTXOver1X,

/*
2.001.29	Measure	High	% of crossover claim headers where MEDICARE-PAID-AMT, TOT-MEDICARE-COINS-AMT, and TOT-MEDICARE-DEDUCTIBLE-AMT are 0 or missing	<= 10% missing	
"IP LT OT"	
This measure should show % of Medicaid and S-CHIP Encounter: Non-void, Crossover, Paid Claims, claim headers where MEDICARE-PAID-AMT, TOT-MEDICARE-COINS-AMT, and TOT-MEDICARE-DEDUCTIBLE-AMT are 0 or missing.	

*/

    CASE WHEN Claim_Type NOT IN ('I','L','O','M','D','H')
        OR CDE_CLM_DISPOSITION IN ('V')
        OR IND_CROSSOVER = 'N'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
    WHEN (  (AMT_PAID_MCARE IS NULL OR AMT_PAID_MCARE <= 0) 
        AND (AMT_COINSURANCE_MCARE IS NULL OR AMT_COINSURANCE_MCARE <= 0)
        AND (AMT_DEDUCT_MCARE IS NULL OR AMT_DEDUCT_MCARE <= 0)
        ) THEN 'INVALID' 
    ELSE 'VALID'
    END AS AmtPaidCoDedMcareHdrXOver1X,

/*
2.001.30	Measure	High	% of non-crossover encounter claims where MEDICARE-PAID-AMT, TOT-MEDICARE-COINS-AMT, or TOT-MEDICARE-DEDUCTIBLE-AMT is non-zero	<= .01% present	
"IP LT OT RX"	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Non-Crossover, Paid Claims  where MEDICARE-PAID-AMT, TOT-MEDICARE-COINS-AMT, and TOT-MEDICARE-DEDUCTIBLE-AMT is not 0.	
*/

    CASE WHEN Claim_Type NOT IN ('I','L','O','M','D','H','P','Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

    WHEN (  (AMT_PAID_MCARE IS NOT NULL AND AMT_PAID_MCARE > 0) 
        OR  (AMT_COINSURANCE_MCARE IS NOT NULL AND AMT_COINSURANCE_MCARE > 0)
        OR  (AMT_DEDUCT_MCARE IS NOT NULL AND AMT_DEDUCT_MCARE > 0)
        ) THEN 'INVALID' 
    ELSE 'VALID'
    END AS AmtPaidCoDedMcareHdrNonXOver1X,

/*
2.001.00	Measure	Medium	Average # ancillary codes on claims with ancillary codes	5-18 Ancillary codes	
IP	
This measure should show the AVE # of ancillary codes on Medicaid and S-CHIP Encounter: Original and Adjustment, Paid Claims with ancillary codes	

Ancillary codes are rev codes 220-998

DTL Processing
*/
/*
    CASE WHEN Claim_Type NOT IN ('I')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
    WHEN DTL_REV_SEQ IS NULL OR DTL_REV_SEQ IN (-1,-4,-5) THEN 'NULL'
--    WHEN DTL_REV_SEQ NOT IN (SELECT REV_SEQ FROM MHDWQA.NW.NW_B_REVENUE_CODE WHERE REV_SEQ = DTL_REV_SEQ AND CDE_REVENUE BETWEEN '220' AND '998') THEN 'INVALID'
    WHEN NOT EXISTS (SELECT REV_SEQ FROM MHDWQA.NW.NW_B_REVENUE_CODE WHERE REV_SEQ = DTL_REV_SEQ AND CDE_REVENUE BETWEEN '220' AND '998') THEN 'INVALID'
    ELSE 'VALID'
    END AS AncillaryCode1X,
*/

    CASE WHEN Claim_Type NOT IN ('I')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

        ELSE (SELECT TO_CHAR(COUNT(rev.REV_SEQ), '999')
                         FROM MHDWQA.SENDPRO.SPRO_B_ENC_INST_INFO_DTL_HIST dtl
                              JOIN MHDWQA.NW.NW_B_REVENUE_CODE rev ON rev.REV_SEQ = dtl.REV_SEQ 
                        WHERE dtl.NUM_ICN = NUM_ICN_HDR
                        AND rev.CDE_REVENUE BETWEEN '220' AND '998')
    END AS AncillaryCode1X,

/*
2.001.02	Measure	Medium	 % missing: ADMITTING-PROV-NUM	<= 2% missing	
IP	
This measure should show the % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing an Admitting Provider PID/SL.	

from dashboard data needed
ATTENDING_ENC_PRV_SEQ
Use this SEQ to match the ENC_PRV_SEQ in the SPRO_B_ENC_PROVIDER_HIST table and select ID_NPI for ADMITTING-PROV-NPI_NUM
*/

    CASE WHEN Claim_Type NOT IN ('I')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
-- like Target
        WHEN attending_ProviderInternalId IS NULL OR attending_ProviderInternalId IN ('#','+','-') THEN 'NULL'
    	WHEN 
             NOT EXISTS (SELECT ENC_PROV_ID from mhdwqa.SENDPRO.spro_b_enc_provider_hist where ENC_PROV_ID NOT IN ('#','+','-') AND ENC_PROV_ID = attending_ProviderInternalId) 
         THEN 'INVALID'
         ELSE 'VALID' 
    END AS AttendingProviderInternalId1X,

/*
2.001.03	Measure	Medium	% missing: ADMITTING-PROV-NPI-NUM	<= 2% missing	
IP	
This measure should show the % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing an Admitting Provider NPI.	
*/

    CASE WHEN Claim_Type NOT IN ('I')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
-- like Target
         WHEN 
               (attending_ProviderNPI IS NULL OR attending_ProviderNPI IN ('#','+','-') OR attending_ProviderNPI IN ('0','000000000','0000000000') ) 
            THEN 'NULL'
		 WHEN 
              (NOT EXISTS (SELECT ID_NPI from mhdwqa.SENDPRO.spro_b_enc_provider_hist where ID_NPI NOT IN ('#','+','-') AND ID_NPI = attending_ProviderNPI))
         THEN 'INVALID'
         ELSE 'VALID' 
    END AS AttendingProviderNPI1X,

/*
2.001.04	Measure	Medium	% missing: ADMISSION-TYPE 	<= 2% missing	
IP	
This measure should show the % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing an Admission Type.	

from final - target
38	MPT_SENDPRO_TypeOfAdmission_Valid	If valid based on the lookup against the CDE_CHAR from NW_SUP_CODE_REF where CDE_GROUP= ‘CDE_ADMIT_TYPE' for Type Of Admission

*/

    CASE WHEN Claim_Type NOT IN ('I')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

-- from Final - Target
        WHEN CDE_ADMIT_TYPE IS NULL OR CDE_ADMIT_TYPE IN ('#','+','-') THEN 'NULL'
        WHEN CDE_ADMIT_TYPE NOT IN (SELECT CDE_CHAR FROM MHDWQA.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_ADMIT_TYPE' AND CDE_CHAR NOT IN ('#','**','+','-','$','  ')) THEN 'INVALID'
        ELSE 'VALID'
    END AS TypeOfAdmission1X,

/*
2.001.05	Measure	Medium	 % missing: BILLED-AMT 	<= 2% missing	
RX	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing the BILLED-AMT	

from Final - Target
55	MPT_SENDPRO_Validate_BilledAmount	If BILLED-AMT is null or less than zero then 0 else 1

Using 2.001.21 where there is no differnece between AMT_BILLED and TOTAL AMT BILLED


    CASE WHEN Claim_Type NOT IN ('P','Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
-- from Target
    WHEN AMT_BILLED IS NULL AND DTL_AMT_BILLED IS NULL THEN 'INVALID'
    WHEN AMT_BILLED <= 0 AND DTL_AMT_BILLED <= 0 THEN 'INVALID'
    ELSE 'VALID'
END AS ClaimBilledAmountRx1X,
*/
    
/*
2.001.07	Measure	Medium	 % missing: BILLING-PROV-TAXONOMY	<= 2% missing	
"IP LT OT"	
This measure should show the % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing Billing Provider Taxonomy.	

*/

    CASE WHEN Claim_Type NOT IN ('I','L','O','M','D','H')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

--  11/19/2025 - debugging
-- from Target
		 WHEN 
         (
             (NOT EXISTS (SELECT tax.CDE_ENC_TAXONOMY from mhdwqa.SENDPRO.spro_b_enc_provider_hist as prv
         LEFT JOIN mhdwqa.SENDPRO.spro_b_enc_provider_taxonomy_hist tax ON prv.ENC_PRV_SEQ = tax.ENC_PRV_SEQ
         where BILLING_ENC_PRV_SEQ = prv.ENC_PRV_SEQ AND tax.CDE_ENC_TAXONOMY IS NOT NULL AND tax.CDE_ENC_TAXONOMY NOT IN ('#','+','-')))

         )
         THEN 'INVALID'
--
         ELSE 'VALID' 
         END AS BillingProviderTaxonomy1X,

/*
2.001.08	Measure	Medium	 % missing: BILLING-PROV-TYPE 	<= 10% missing	
OT	
This measure should show the % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing Billing Provider Type.	

from dashboard data needed

"All:
SPRO_B_ENC_PROVIDER_HIST.ENC_PRV_SEQ
SPRO_B_ENC_PROVIDER_HIST.CDE_ENC_PROV_TYPE
Phys:
SPRO_B_ENC_CLAIM_PROF_LEG_HIST.BILLING_ENC_PRV_SEQ
Dental:
SPRO_B_ENC_CLAIM_DNTL_LEG_HIST.BILLING_ENC_PRV_SEQ
OutP:
SPRO_B_ENC_CLAIM_INST_LEG_HIST.BILLING_ENC_PRV_SEQ"	

"Use the BILLING_ENC_PRV_SEQ from the SPRO_B_ENC_CLAIM_PROF_LEG_HIST, SPRO_B_ENC_CLAIM_DNTL_LEG_HIST, and  SPRO_B_ENC_CLAIM_INST_LEG_HIST tables 
to match the ENC_PRV_SEQ in the SPRO_B_ENC_PROVIDER_HIST table and select CDE_ENC_PROV_TYPE for the BILLING-PROV-TYPE
Use current Prov_Type crosswalk to map to CMS valid value.

If multiple values, pick the first one"

?? used Final code but logic may be more thorough

*/

    CASE WHEN Claim_Type NOT IN ('O','M','D','H')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
-- from Target for Serving Provider Type
		 WHEN 
         (
              (NOT EXISTS (SELECT prv.CDE_ENC_PROV_TYPE from mhdwqa.SENDPRO.spro_b_enc_provider_hist as prv
         where BILLING_ENC_PRV_SEQ = prv.ENC_PRV_SEQ AND prv.CDE_ENC_PROV_TYPE IS NOT NULL AND prv.CDE_ENC_PROV_TYPE NOT IN ('#','+','-')))
         )
         THEN 'INVALID'
         ELSE 'VALID' 
         END AS BillingProviderType1X,


/*
2.001.09	Measure	Medium	 % missing: BRAND-GENERIC-IND 	<= 10% missing	
RX	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing BRAND-GENERIC-IND	

?? how about standardizing this to 'Y' or 'N'  OR 'B' or 'G'
IND_GENERIC
CMS wants Y and N only
*/

    CASE WHEN Claim_Type NOT IN ('P','Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
        WHEN IND_GENERIC IS NULL OR IND_GENERIC IN ('#','+','-') OR IND_GENERIC NOT IN ('Y','N','B','G')  THEN 'INVALID'
        ELSE 'VALID'
        END AS BrandGenericInd1X,

/*
2.001.10	Measure	Medium	% missing: COMPOUND-DRUG-IND 	1-99% missing	
RX	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing COMPOUND-DRUG-IND	

A Claim_Type 'Q' indicates a compund drug claim. Shall we use this as an indicator of compund drugs?
Code as 1(compound) Claim_Type=Q. Else code as 0

?? Couuld add:

50	MPT_SENDPRO_NDC_Valid_ALL	If valid based on lookup to the column CDE_NDC from "NW_B_DRUG" then 1 else 0

CASE
    WHEN (IND_SCRIPT_OT = 'O') OR (DTL_CDE_NDC IS NULL) THEN 'NOT APP'
    WHEN NOT EXISTS (SELECT CDE_NDC FROM MHDWQA.NW.NW_B_DRUG WHERE CDE_NDC = DTL_CDE_NDC AND CDE_NDC NOT IN ('#','**','+','-','$','  ')) 
	THEN 'INVALID'
    ELSE 'VALID'
END AS CompoundNDC1X,

*/

    CASE WHEN Claim_Type NOT IN ('Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

    WHEN (IND_SCRIPT_OT = 'O') THEN 'NOT APP'
    WHEN NOT EXISTS (SELECT CDE_NDC FROM MHDWQA.NW.NW_B_DRUG WHERE CDE_NDC = PHRM_CDE_NDC AND CDE_NDC NOT IN ('#','**','+','-','$','  ')) 
	THEN 'INVALID'

        ELSE 'VALID'
    END AS CompoundDrugInd1X,


/*
2.001.11	Measure	Medium	 % missing: DISPENSING-PRESCRIPTION-DRUG-PROV-NUM	<= 2% missing	
RX	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing Dispensing PID/SL	

?? RX has Billing and Prescribing providers - is Dispensing same as Billing?
If yes, could add RX to 01

-- Using Billing Provider Internal Location from 2.001.06
*/


/*
2.001.12	Measure	Medium	% missing: MEDICAID-COV-INPATIENT-DAYS	<= 2% missing	
IP	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing MEDICAID-COV-INPATIENT-DAYS	

SPRO_B_ENC_CLAIM_INST_LEG_HIST.NUM_DAYS_COVD

*/

    CASE WHEN Claim_Type NOT IN ('I')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
    WHEN NUM_DAYS_COVD IS NULL OR NUM_DAYS_COVD < 0 THEN 'INVALID'
    ELSE 'VALID'
    END AS MedicaidCovInpatientDays1X,

/*
2.001.13	Measure	Medium	 % missing: PRESCRIBING-PROV-NUM 	<= 10% missing	
RX	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing Prescribing Provider PID/SL	
*/

    CASE WHEN Claim_Type NOT IN ('P','Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
-- From Target
         WHEN prescribing_ProviderInternalId IS NULL OR prescribing_ProviderInternalId IN ('#','+','-') THEN 'NULL'
		 WHEN 
         (
              (NOT EXISTS (SELECT ENC_PROV_ID from mhdwqa.SENDPRO.spro_b_enc_provider_hist where ENC_PROV_ID NOT IN ('#','+','-') AND ENC_PROV_ID = prescribing_ProviderInternalId)) 
         )
         THEN 'INVALID'
         ELSE 'VALID' 
         END AS PrescribingProviderInternalId1X,

/*
2.001.14	Measure	Medium	 % missing: PRESCRIBING-PROV-NPI-NUM 	<= 2% missing	
RX	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing Prescribing Provider NPI	
*/

    CASE WHEN Claim_Type NOT IN ('P','Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
-- From Target
         WHEN 
                (prescribing_ProviderNPI IS NULL OR prescribing_ProviderNPI IN ('#','+','-') OR prescribing_ProviderNPI IN ('0','000000000','0000000000')) 
         THEN 'NULL'
            
         WHEN 
              (NOT EXISTS (SELECT ID_NPI from mhdwqa.SENDPRO.spro_b_enc_provider_hist where ID_NPI NOT IN ('#','+','-') AND ID_NPI = prescribing_ProviderNPI))
         THEN 'INVALID'
         ELSE 'VALID' 
         END AS PrescribingProviderNPI1X,

/*
2.001.15	Measure	Medium	% missing: REVENUE-CHARGE 	<= 2% missing	
"IP LP"	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing REVENUE-CHARGE	

Dont see Revenue Charge field

From dashboard data needed

IP	SPRO_B_ENC_INST_INFO_DTL_HIST.AMT_BILLED
LT	SPRO_B_ENC_INST_INFO_DTL_HIST.AMT_SVC_LINE_CHARGE

see  SVCLINECHARGEAMT only found in STG_B_ENC_PROF_INFO_DTL_SCRUB_* tables

Same as Amt_Billed - 2.001.21
*/


/*
2.001.16	Measure	Medium	% missing: REBATE-ELIGIBLE-INDICATOR 	<= 20% missing	
RX	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing REBATE-ELIGIBLE-INDICATOR	


Using SPRO_B_ENC_CLAIM_PHRM_LEG_HIST.AMT_PATIENT_FORM_REBATE

*/

    CASE WHEN Claim_Type NOT IN ('P','Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

         WHEN AMT_PATIENT_FORM_REBATE IS NULL THEN 'INVALID'
         WHEN AMT_PATIENT_FORM_REBATE < 0 THEN 'INVALID'
         ELSE 'VALID'  
         END AS RebateEligibleInd1X,

/*
2.001.17	Measure	Medium	% missing: REFERRING-PROV-NUM 	<= 98% missing	
OT	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing Referring Provider PID/SL	
*/

    CASE WHEN Claim_Type NOT IN ('O','M','D','H')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

-- From Target Servicing Provider Internal ID
         WHEN (Referring_ProviderInternalId IS NULL) THEN 'NULL'

--		 WHEN 
--         (
--              (NOT EXISTS (SELECT ENC_PROV_ID from mhdwqa.SENDPRO.spro_b_enc_provider_hist where ENC_PROV_ID NOT IN ('#','+','-') AND ENC_PROV_ID = Referring_ProviderInternalId)) 
--          AND (NOT EXISTS (SELECT ENC_PROV_ID from mhdwqa.SENDPRO.spro_b_enc_provider_hist where ENC_PROV_ID NOT IN ('#','+','-') AND ENC_PROV_ID = dtl_referring_ProviderInternalId))
--         )
--         THEN 'INVALID'

-- Servicing Internal Provider Address Location

		 WHEN 
         (
             (NOT EXISTS (SELECT prv.ID_PROVIDER_LOCATION from mhdwqa.SENDPRO.spro_b_enc_provider_hist as prv
         where SERVICING_ENC_PRV_SEQ = prv.ENC_PRV_SEQ AND prv.ID_PROVIDER_LOCATION IS NOT NULL AND prv.ID_PROVIDER_LOCATION NOT IN ('#','+','-')))

         )
         THEN 'INVALID'

         ELSE 'VALID' 
         END AS ReferringProviderInternalId1X,

/*
2.001.18	Measure	Medium	% missing: REFERRING-PROV-NPI-NUM	>= 90% present	
IP	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing Referring Provider NPI	
*/

    CASE WHEN Claim_Type NOT IN ('I')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'

-- From Target Servicing Provider NPI
         WHEN 
         (
                (Referring_ProviderNPI IS NULL OR Referring_ProviderNPI IN ('#','+','-') OR Referring_ProviderNPI IN ('0','000000000','0000000000')) 
         )            
         THEN 'NULL'
            
         WHEN 
         (
              (NOT EXISTS (SELECT ID_NPI from mhdwqa.SENDPRO.spro_b_enc_provider_hist where ID_NPI NOT IN ('#','+','-') AND ID_NPI = Referring_ProviderNPI)) 
         )
         THEN 'INVALID'
         ELSE 'VALID' 
         END AS ReferringProviderNPI1X,


/*
2.001.19	Measure	Medium	% missing: SERVICING-PROV-NUM	<= 10% missing	
OT	
This measure should show % of Medicaid and S-CHIP Encounter: Original and Replacement, Paid Claims missing Servicing Provider PID/SL	
*/
    
    CASE WHEN Claim_Type NOT IN ('O','M','D','H')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
-- From Target Servicing Provider Internal ID
         WHEN (servicing_ProviderInternalId IS NULL) THEN 'NULL'
		 WHEN 
         (
              (NOT EXISTS (SELECT ENC_PROV_ID from mhdwqa.SENDPRO.spro_b_enc_provider_hist where ENC_PROV_ID NOT IN ('#','+','-') AND ENC_PROV_ID = servicing_ProviderInternalId)) 
         )
         THEN 'INVALID'
         ELSE 'VALID' 
         END AS ServicingProviderInternalId1X,

/*
2.001.20	Measure	Medium	% missing: TOT-ALLOWED-AMT 	<= 2% missing	
"IP LT OT RX"	
This measure should show % of IP, LT, OT, and RX claims missing Total Allowed Amount 	
*/

    CASE WHEN Claim_Type NOT IN ('I','L','O','M','D','H','P','Q')
        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        OR CDE_CLM_STATUS != 'P'
        THEN 'NOT APP'
-- from Target
    WHEN AMT_ALLOWED IN (-1,-4,-5) THEN 'INVALID'
    WHEN AMT_ALLOWED <= 0 THEN 'INVALID'
    ELSE 'VALID'
END AS ClaimAllowableAmount1X,

------

CASE WHEN Claim_Type = 'I' THEN 1 ELSE 0 END INPAT_HDR,
CASE WHEN Claim_Type = 'O' THEN 1 ELSE 0 END OUTPAT_HDR,
CASE WHEN Claim_Type = 'L' THEN 1 ELSE 0 END LTC_HDR,
CASE WHEN Claim_Type = 'M' THEN 1 ELSE 0 END PROF_HDR,
CASE WHEN Claim_Type = 'H' THEN 1 ELSE 0 END HOME_HDR,
CASE WHEN Claim_Type = 'D' THEN 1 ELSE 0 END DENT_HDR,
CASE WHEN Claim_Type = 'P' THEN 1 ELSE 0 END PHARM_HDR,
CASE WHEN Claim_Type = 'Q' THEN 1 ELSE 0 END COMPOUND_HDR,
CASE WHEN Claim_Type NOT IN  ('P', 'Q') THEN 1 ELSE 0 END AS NON_PHARM_HDR,

    CASE WHEN Claim_Type IN ('I') 
        AND CDE_CLM_DISPOSITION IN ('O','A')
        AND IND_CROSSOVER != 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END IP_OA_NX_P,

    CASE WHEN Claim_Type IN ('I')
        AND CDE_CLM_DISPOSITION IN ('O')
        AND IND_CROSSOVER != 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END IP_O_NX_P,

    CASE WHEN Claim_Type IN ('I')
        AND CDE_CLM_DISPOSITION IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END IP_OA_P,

    CASE WHEN Claim_Type IN ('L')
        AND CDE_CLM_DISPOSITION IN ('O')
        AND IND_CROSSOVER = 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END LT_O_X_P,

    CASE WHEN Claim_Type IN ('I','L')
        AND CDE_CLM_DISPOSITION IN ('O')
        AND IND_CROSSOVER != 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END IPLT_O_NX_P,

    CASE WHEN Claim_Type IN ('O','M','D','H')
        AND CDE_CLM_DISPOSITION IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END OT_OA_P,

    CASE WHEN Claim_Type IN ('I','L','O','M','D','H')
        AND CDE_CLM_DISPOSITION IN ('O','A')
        AND IND_CROSSOVER != 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END IPLTOT_OA_NX_P,

    CASE WHEN Claim_Type IN ('I','L','O','M','D','H')
        AND CDE_CLM_DISPOSITION IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END IPLTOT_OA_P,

    CASE WHEN Claim_Type IN ('P','Q')
        AND CDE_CLM_DISPOSITION IN ('O','A')
        AND IND_CROSSOVER != 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END RX_OA_NX_P,

    CASE WHEN Claim_Type IN ('P','Q')
        AND CDE_CLM_DISPOSITION IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END RX_OA_P,

    CASE WHEN Claim_Type IN ('Q')
        AND CDE_CLM_DISPOSITION IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END Q_OA_P,

    CASE WHEN Claim_Type IN ('I','L','P','Q')
        AND CDE_CLM_DISPOSITION IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END IPLTRX_OA_P,

    CASE WHEN Claim_Type IN ('I','O','M','D','H','P','Q')
        AND CDE_CLM_DISPOSITION IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END IPOTRX_OA_P,

    CASE WHEN Claim_Type IN ('I','L','O','M','D','H','P','Q')
        AND CDE_CLM_DISPOSITION IN ('O','A')
        --OR IND_CROSSOVER = 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END IPLTOTRX_OA_P,

    CASE WHEN Claim_Type IN ('I','L','O','M','H','D','P','Q') 
--        OR CDE_CLM_DISPOSITION NOT IN ('O','A')
--        OR IND_CROSSOVER = 'Y'
        AND CDE_CLM_STATUS = 'D'
        THEN 1 ELSE 0 END IPLTOTRX_D,

    CASE WHEN Claim_Type IN ('I','O','M','L','H','D','P','Q') 
        AND CDE_CLM_DISPOSITION IN ('O','A')
        AND IND_CROSSOVER != 'Y'
        AND CDE_CLM_STATUS = 'P'
        THEN 1 ELSE 0 END IPLTOTRX_OA_NX_P,

1 as TOT_REX_HDR

FROM MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_EXTRACT_HDR;

