-- or use DATE RUN table

DROP VIEW INF_SENDPRO_TMSIS_RUN_DATE;

CREATE VIEW INF_SENDPRO_TMSIS_RUN_DATE
AS
SELECT RUN_DATE 
FROM MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_RUN_DATE;

SELECT * FROM MHTEAM.DWDQ.INF_SENDPRO_TMSIS_RUN_DATE;

TRUNCATE TABLE MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_RUN_DATE;

SELECT * FROM MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_RUN_DATE;

INSERT INTO MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_RUN_DATE
SELECT CURRENT_DATE() AS RUN_DATE;

CREATE TABLE MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_RUN_DATE
AS
SELECT CURRENT_DATE() AS RUN_DATE;

-- in Informatica
UPDATE MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_RUN_DATE
SET RUN_DATE = (SELECT CURRENT_DATE());

