drop table MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP;

create table MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP
(
BENCHMARK              varchar(100),
BENCHMARK_THRESHOLD    number(3,2),
PRIORITY               varchar(20)
);

TRUNCATE TABLE INF_B_SENDPRO_TMSIS_LOOKUP;

/*
select 'insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES (''' || measure || ''', 1.0 , ''Not Set'');'  
from (
select distinct measure
from MHTEAM.DWDQ.INF_SENDPRO_TMSIS_837_HDR_UNPIV
)
order by measure;
*/

/*
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADJUDICATION_DATE_DETAIL', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADJUDICATION_DATE_HEADER', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADMISSION_TYPE_CODE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ALLOWED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_DTL', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_HDR', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_LT_XOVER', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_NON_XOVER_WDATA', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_XOVER_MISSING', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_INTERNAL_ADDRESS_LOCATION', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_TAXONOMY', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_TYPE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BRAND_GENERIC_IND', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('COMPOUND_DRUG_IND', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('MEDICAID_COVERAGE_INPATIENT_DAYS', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('MEMBER_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PATIENT_STATUS_CODE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIPTION_FILL_DATE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REBATE_ELIGIBLE_INDICATOR', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REVENUE_CODE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_INTERNAL_ADDRESS_LOCATION', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('STATEMENT_DATE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('TO_SERVICE_DATE', 1.0);

--delete from INF_B_SENDPRO_TMSIS_LOOKUP where BENCHMARK = 'BILLED_AMOUNT_RX';
--insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLED_AMOUNT_RX', 1.0);
--insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_INTERNAL_ID', 1.0);
--insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_INTERNAL_ID', 1.0);
*/

insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('ACCOMODATION_REVENUE_CODE', 0.85 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('ADJUDICATION_DATE_DETAIL', 1.0 , 'Critical');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('ADJUDICATION_DATE_HEADER', 1.0 , 'Critical');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('ADMISSION_TYPE_CODE', 0.98 , 'Medium');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('ALLOWED_AMOUNT', 0.98 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('AMOUNT_PAID_MEDICARE_LT_XOVER', 0.6 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('AMOUNT_PAID_MEDICARE_MEDICAID', 0.90 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('AMOUNT_PAID_MEDICARE_NON_XOVER_WDATA', 0.99 , 'High');
--insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('AMOUNT_PAID_MEDICARE_SCHIP', 1.0 , 'Not Set');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('AMOUNT_PAID_MEDICARE_XOVER_MISSING', 0.90 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('ATTENDING_PROVIDER_INTERNAL_ID', 1.0 , 'Not Set');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('ATTENDING_PROVIDER_NPI', 1.0 , 'Not Set');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('BILLED_AMOUNT', 0.98 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('BILLING_PROVIDER_PIDSL', 0.98 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('BILLING_PROVIDER_NPI', 0.98 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('BILLING_PROVIDER_TAXONOMY', 0.98 , 'Medium');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('BILLING_PROVIDER_TYPE', 0.90 , 'Medium');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('BRAND_GENERIC_IND', 0.90 , 'Medium');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('COMPOUND_DRUG_IND', 0.01 , 'Medium');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('DENIED_HDRS_NO_LINES', 1.0 , 'Critical');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('MEDICAID_COVERED_INPATIENT_DAYS', 0.98 , 'Critical');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('MSIS_IDENTIFICATION_NUMBER', 0.98 , 'Critical');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('PAID_HDRS_NO_LINES', 1.0 , 'Critical');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('PAID_HDRS_NO_NON_DENIED_LINES', 1.0 , 'Critical');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('PATIENT_STATUS_CODE', 0.95 , 'Critical');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('PRESCRIBING_PROVIDER_INTERNAL_ID', 0.90 , 'Medium');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('PRESCRIBING_PROVIDER_NPI', 0.98 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('PRESCRIPTION_FILL_DATE', 0.98 , 'Critical');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('REBATE_ELIGIBLE_INDICATOR', 0.80 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('REFERRING_PROVIDER_INTERNAL_ID', 0.02 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('REFERRING_PROVIDER_NPI', 0.90 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('SERVICING_PROVIDER_PIDSL', 0.90 , 'High');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('BEGINNING_DATE_OF_SERVICE', 0.98 , 'Critical');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY) VALUES ('ENDING_DATE_OF_SERVICE', 0.98 , 'Critical');

commit;