drop table INF_B_SENDPRO_TMSIS_LOOKUP;

create table INF_B_SENDPRO_TMSIS_LOOKUP
(
BENCHMARK              varchar(100),
BENCHMARK_THRESHOLD    number(3,2)
);


TRUNCATE TABLE INF_B_SENDPRO_TMSIS_LOOKUP;

select 'insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES (''' || measure || ''', 1.0);'  
from (
select distinct measure
from MHTEAM.DWDQ.INF_SENDPRO_TMSIS_837_UNPIV
)
order by measure;

insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADMISSION_TYPE_CODE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ALLOWED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_DTL', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_HDR', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_LT_XOVER', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_NON_XOVER_WDATA', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_XOVER_MISSING', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLED_AMOUNT_RX', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_TAXONOMY', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_TYPE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BRAND_GENERIC_IND', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('COMPOUND_DRUG_IND', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('MEDICAID_COVERAGE_INPATIENT_DAYS', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('MEMBER_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PATIENT_STATUS_CODE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIPTION_FILL_DATE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REBATE_ELIGIBLE_INDICATOR', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REVENUE_CODE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('STATEMENT_DATE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('TO_SERVICE_DATE', 1.0);