--drop table MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP;

--create table MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP
--(
--REQ_NO                 number,
--BENCHMARK              varchar(100),
--BENCHMARK_THRESHOLD    number(3,2),
--PRIORITY               varchar(20),
--TMSIS_CLAIM_TYPE       varchar(20),
--TMSIS_CLAIM_TYPE_DSC   varchar(100)
--);

--select * from MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP;

TRUNCATE TABLE INF_B_SENDPRO_TMSIS_LOOKUP;

/*
select 'insert into INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (''' || measure || ''', 1.0 , ''Not Set'');'  
from (
select distinct measure
from MHTEAM.DWDQ.INF_SENDPRO_TMSIS_837_HDR_UNPIV
)
order by measure;
*/

/*
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADJUDICATION_DATE_DETAIL', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADJUDICATION_DATE_HEADER', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADMISSION_TYPE_CODE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ALLOWED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_DTL', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_HDR', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_LT_XOVER', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_NON_XOVER_WDATA', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('AMOUNT_PAID_MEDICARE_XOVER_MISSING', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_INTERNAL_ADDRESS_LOCATION', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_TAXONOMY', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_TYPE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BRAND_GENERIC_IND', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('COMPOUND_DRUG_IND', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('MEDICAID_COVERAGE_INPATIENT_DAYS', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('MEMBER_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PATIENT_STATUS_CODE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIPTION_FILL_DATE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REBATE_ELIGIBLE_INDICATOR', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REVENUE_CODE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_INTERNAL_ADDRESS_LOCATION', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('STATEMENT_DATE', 1.0);
insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('TO_SERVICE_DATE', 1.0);

--delete from INF_B_SENDPRO_TMSIS_LOOKUP where BENCHMARK = 'BILLED_AMOUNT_RX';
--insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLED_AMOUNT_RX', 1.0);
--insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_INTERNAL_ID', 1.0);
--insert into INF_B_SENDPRO_TMSIS_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_INTERNAL_ID', 1.0);
*/

insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (22, 'ACCOMODATION_REVENUE_CODE', 0.85 , 'High','IP_O_NX_P','Inpatient_Orig_NonXOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (37, 'ADJUDICATION_DATE_DETAIL', 1.0 , 'Critical', 'IPLTOTRX_OA_NX_P', 'All Claim Types_Orig&Adj_NonXOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (36, 'ADJUDICATION_DATE_HEADER', 1.0 , 'Critical', 'IPLTOTRX_OA_NX_P', 'All Claim Types_Orig&Adj_NonXOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (4, 'ADMISSION_TYPE_CODE', 0.98 , 'Medium', 'IP_OA_P', 'Inpatient_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (20, 'ALLOWED_AMOUNT', 0.98 , 'High', 'IPLTOTRX_OA_P', 'All Claim Types_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (26, 'AMOUNT_PAID_MEDICARE_LT_XOVER', 0.6 , 'High', 'LT_O_X_P', 'LTC_Original_CrossOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (24, 'AMOUNT_PAID_MEDICARE_MEDICAID', 0.90 , 'High', 'IP_O_NX_P', 'Inpatient_Orig_NonXOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (30, 'AMOUNT_PAID_MEDICARE_NON_XOVER_WDATA', 0.99 , 'High', 'IPLTOTRX_OA_NX_P', 'All Claim Types_Orig&Adj_NonXOver_Paid');
--insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES ('AMOUNT_PAID_MEDICARE_SCHIP', 1.0 , 'Not Set');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (29, 'AMOUNT_PAID_MEDICARE_XOVER_MISSING', 0.90 , 'High', 'IPLTOT_OA_X_P', 'Inpatient_LTC_Other_Origi&Adj_XOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (2, 'ATTENDING_PROVIDER_INTERNAL_ID', 1.0 , 'Not Set', 'IP_OA_P', 'Inpatient_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (3, 'ATTENDING_PROVIDER_NPI', 1.0 , 'Not Set', 'IP_OA_P', 'Inpatient_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (21, 'BILLED_AMOUNT', 0.98 , 'High', 'IPLTRX_OA_P', 'Inpatient_LTC_Pharmacy_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (6, 'BILLING_PROVIDER_PIDSL', 0.98 , 'High', 'IPOTRX_OA_P', 'Inpatient_Other_Pharmacy_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (1, 'BILLING_PROVIDER_NPI', 0.98 , 'High', 'RX_OA_P', 'Pharmacy_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (7, 'BILLING_PROVIDER_TAXONOMY', 0.98 , 'Medium', 'IPLTOT_OA_P', 'Inpatient_LTC_Other_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (8, 'BILLING_PROVIDER_TYPE', 0.90 , 'Medium', 'OT_OA_P', 'Other_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (9, 'BRAND_GENERIC_IND', 0.90 , 'Medium', 'RX_OA_P', 'Pharmacy_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (10, 'COMPOUND_DRUG_IND', 0.01 , 'Medium', 'Q_OA_P', 'Compound_Only_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (39, 'DENIED_HDRS_NO_LINES', 1.0 , 'Critical', 'IPLTOTRX_D', 'Inpatient_LTC_Pharmacy_Denied');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (12, 'MEDICAID_COVERED_INPATIENT_DAYS', 0.98 , 'Critical', 'IP_OA_P', 'Inpatient_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (32, 'MSIS_IDENTIFICATION_NUMBER', 0.98 , 'Critical', 'IPLTOTRX_OA_NX_P', 'All Claim Types_Orig&Adj_NonXOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (38, 'PAID_HDRS_NO_LINES', 1.0 , 'Critical', 'IPLTOTRX_OA_NX_P', 'All Claim Types_Orig&Adj_NonXOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (41, 'PAID_HDRS_NO_NON_DENIED_LINES', 1.0 , 'Critical', 'IPLTOTRX_OA_NX_P', 'All Claim Types_Orig&Adj_NonXOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (31, 'PATIENT_STATUS_CODE', 0.95 , 'Critical', 'IP_OA_NX_P', 'Inpatient_Orig&Adj_NonXOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (13, 'PRESCRIBING_PROVIDER_INTERNAL_ID', 0.90 , 'Medium', 'RX_OA_P', 'Pharmacy_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (14, 'PRESCRIBING_PROVIDER_NPI', 0.98 , 'High', 'RX_OA_P', 'Pharmacy_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (44, 'PRESCRIPTION_FILL_DATE', 0.98 , 'Critical', 'RX_OA_NX_P', 'Pharmacy_Orig&Adj_NonXOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (16, 'REBATE_ELIGIBLE_INDICATOR', 0.80 , 'High', 'RX_OA_P', 'Pharmacy_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (17, 'REFERRING_PROVIDER_INTERNAL_ID', 0.02 , 'High', 'OT_OA_P', 'Other_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (18, 'REFERRING_PROVIDER_NPI', 0.90 , 'High', 'IP_OA_P', 'Inpatient_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (19, 'SERVICING_PROVIDER_PIDSL', 0.90 , 'High', 'OT_OA_P', 'Other_Orig&Adj_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (42, 'BEGINNING_DATE_OF_SERVICE', 0.98 , 'Critical', 'IPLTOT_OA_NX_P', 'Inpatient_LTC_Other_Orig&Adj_NonXOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (43, 'ENDING_DATE_OF_SERVICE', 0.98 , 'Critical', 'IPLTOT_OA_NX_P', 'Inpatient_LTC_Other_Orig&Adj_NonXOver_Paid');

insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (33, 'PAID_LINES_NO_HDRS', 1.0 , 'Critical', 'IPLTOTRX_OA_NX_P', 'Inpatient_LTC_Other_Orig&Adj_NonXOver_Paid');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (33, 'DENIED_LINES_NO_HDRS', 1.0 , 'Critical', 'IPLTOTRX_D', 'Inpatient_LTC_Pharmacy_Denied');
insert into MHTEAM.DWDQ.INF_B_SENDPRO_TMSIS_LOOKUP ( REQ_NO, BENCHMARK, BENCHMARK_THRESHOLD, PRIORITY, TMSIS_CLAIM_TYPE, TMSIS_CLAIM_TYPE_DSC) VALUES (0, 'ANCILLARY CODES', 0.0 , 'Medium', 'IPLT_OA_P', 'Inpatient_LTC_Orig&Adj_Paid');


commit;